version: '3'
services:
  nginx:
   image: 'nginx:alpine'
   container_name: 'nginx'
   depends_on:
      - nodeapp
   volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   ports:
      - '80:80'
   networks:
      - proxy
  nodeapp:
    image: 'nodeapp'
    container_name: 'nodeapp'
    ports:
      - '8000:8000'
    networks:
      - proxy
      - db
networks:
  proxy:
  db: